app/acis/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'', include('cms.urls')),
]

app/cms/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

from cms.views.sitemap import CategoriesSitemap, PostsSitemap, StaticSitemap
from cms.views import post, ajax, comment, profile, map, registration

from cms.forms.registration import RememberAuthenticationForm
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from cms.views.rss import LatestEntriesFeed

sitemaps = {
    'categories': CategoriesSitemap,
    'static': StaticSitemap,
    'posts': PostsSitemap,
}

urlpatterns = [
    url(r'^$', post.post_list, name='post_list'),
    url(r'^post/new/$', post.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/$', post.post_detail, name='post_detail'),

    url(r'^post/(?P<pk>[0-9]+)/edit/$', post.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>[0-9]+)/delete/$', post.post_delete, name='post_delete'),

    url(r'^post/(?P<pk>[0-9]+)/comment/new/$', comment.comment_new, name='comment_new'),
    url(r'^post/(?P<pk>[0-9]+)/comment(?P<cpk>[0-9]+)/reply/$', comment.comment_reply, name='comment_reply'),
    url(r'^post/(?P<pk>[0-9]+)/comment(?P<cpk>[0-9]+)/edit/$', comment.comment_edit, name='comment_edit'),
    url(r'^post/(?P<pk>[0-9]+)/comment(?P<cpk>[0-9]+)/delete/$', comment.comment_delete, name='comment_delete'),

    url(r'^author/(?P<author>[\w\.@+\-]+)?/$', post.post_list, name='author_list'),
    url(r'^author/(?P<author>[\w\.@+\-]+)/tags/(?P<tags>[\w\s\d\-_,]+)?/$', post.post_list, name='author_tags_list'),

    url(r'^category/(?P<category>\w+)?/$', post.post_list, name='category_list'),
    url(r'^category/(?P<category>\w+)/tags/(?P<tags>[\w\s\d\-_,]+)?/$', post.post_list, name='category_tags_list'),

    url(r'^tags/(?P<tags>[\w\s\d\-_,]+)/$', post.post_list, name='tag_list'),

    url(r'^maps/$', map.maps_list, name='maps_list'),
    url(r'^maps/new/$', map.map_new, name='map_new'),
    url(r'^maps/(?P<pk>[0-9]+)/$', map.serve_map_file, name='map_file'),
    url(r'^maps/(?P<pk>[0-9]+)/edit/$', map.map_edit, name='map_edit'),
    url(r'^maps/(?P<pk>[0-9]+)/delete/$', map.map_delete, name='map_delete'),

    url(r'^maps/author/(?P<author>[\w\.@+\-]+)?/$', map.maps_list, name='maps_author_list'),
    url(r'^maps/author/(?P<author>[\w\.@+\-]+)/tags/(?P<tags>[\w\s\d\-_,]+)?/$', map.maps_list, name='maps_author_tags_list'),

    url(r'^maps/tags/(?P<tags>[\w\s\d\-_,]+)/$', map.maps_list, name='maps_tag_list'),

    url(r'^accounts/login/$', registration.remember_login, {
        'template_name': 'registration/login.html',
        'authentication_form': RememberAuthenticationForm
    }, name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page=reverse_lazy('post_list')),
        name='auth_logout'),

    url(r'^accounts/register/$', registration.registration, name='registration_register'),
    url(r'^accounts/register/confirm/(?P<activation_key>[-:\w]+)/$', registration.activation,
        name='registration_confirm'),

    url(r'^accounts/password/change/$',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('auth_password_change_done')
        ),
        name='auth_password_change'),
    url(r'^accounts/password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='auth_password_change_done'),
    url(r'^accounts/password/reset/$',
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy('auth_password_reset_done')
        ),
        name='auth_password_reset'),
    url(r'^accounts/password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='auth_password_reset_complete'),
    url(r'^accounts/password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='auth_password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('auth_password_reset_complete')
        ),
        name='auth_password_reset_confirm'),

    url(r'^accounts/email/change/$', registration.edit_email, name='auth_email_change'),
    url(r'^accounts/email/change/done/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', registration.edit_email_done, name='auth_email_change_done'),

    url(r'^accounts/me/$', profile.my_profile, name='me'),
    url(r'^accounts/me/edit/$', profile.profile_edit, name='me_edit'),
    url(r'^accounts/user/(?P<username>[\w\.@+\-]+)/$', profile.profile, name='user'),
    url(r'^accounts/user/(?P<username>[\w\.@+\-]+)/edit/$', profile.profile_edit, name='user_edit'),
    url(r'^accounts/userlist/$', profile.userlist, name='users_list'),

    url(r'^upload/', post.upload, name='ckeditor_upload'),

    url(r'^ajax/tags/', ajax.get_simular_tags, name="get_simular_tags"),

    url(r'^messages/', include('vendors.django_messages.urls')),

    url(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^latest/feed/', LatestEntriesFeed(), name="feed_latest"),
    url(r'^webpush/', include('webpush.urls')),
    url('', include('social_django.urls', namespace='social')),

    url(r'donated/', TemplateView.as_view(template_name='donated.html'), name='donated'),
]

if settings.ENV == 'development':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/diggers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'', include('cms.urls')),
]

app/cms/models/cmspost.py
from django.db import models
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.template.defaultfilters import truncatechars
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

from .comment import Comment

class CmsPost(models.Model):
    author = models.ForeignKey('auth.User', verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    category = models.ForeignKey('CmsCategory', blank=True, null=False, verbose_name='Категорія')

    text = RichTextUploadingField(verbose_name='Текст')

    tags = TaggableManager(blank=True, verbose_name='Тэги')
    created_date = models.DateTimeField(default=timezone.now, verbose_name='Дата створення')
    modifed_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата редагування')
    is_permited = models.BooleanField(default=False, verbose_name='Зробити прихованим')

    last_comment = models.ForeignKey('Comment', verbose_name='Останній коментар', blank=True, null=True, on_delete=models.SET_NULL)

    @property
    def short_title(self):
        return truncatechars(self.title, 100)

    @property
    def short_text(self):
        return truncatechars(self.text, 800)

    def _tags(self):
        return [t.name for t in self.tags.all()]

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    @receiver(post_save, sender=Comment)
    def change_last_comment_on_create(sender, instance, created, **kwargs):
        post = CmsPost.objects.get(pk=instance.post.pk)

        if created:
            post.last_comment = instance
        else:
            if instance.is_deleted:
                post.last_comment = Comment.objects.filter(post=instance.post, is_deleted=False).order_by('-created_date').first()

        post.save()

    @receiver(post_delete, sender=Comment)
    def change_last_comment_on_delete(sender, instance, **kwargs):
        post = CmsPost.objects.get(pk=instance.post.pk)
        post.last_comment = Comment.objects.filter(post=instance.post, is_deleted=False).order_by('-created_date').first()
        post.save()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        permissions = (
            ('moderate_cmspost', 'Модерація постів'),
            ('permited_access', 'Доступ до прихованих постів'),
        )

app/cms/models/comment.py
from django.db import models
from django.template.defaultfilters import truncatechars
from mptt.models import MPTTModel, TreeForeignKey
from django.utils import timezone
from simplemde.fields import SimpleMDEField


class Comment(MPTTModel):
    post = models.ForeignKey('CmsPost', on_delete=models.CASCADE, verbose_name='Пост')
    author = models.ForeignKey('auth.User', verbose_name='Автор')
    text = SimpleMDEField(verbose_name='Текст')

    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            verbose_name='Відповідь на')

    is_deleted = models.BooleanField(default=False, verbose_name='Видалено')

    created_date = models.DateTimeField(default=timezone.now, verbose_name='Дата створення', unique=True)
    modifed_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата редагування')

    def __str__(self):
        return self.text

    @property
    def short_text(self):
        return truncatechars(self.text, 50)

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        permissions = (
            ('moderate_comment', 'Модерація коментарів'),
        )

    class MPTTMeta:
        order_insertion_by = ['created_date']

app/cms/models/map.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import truncatechars
from taggit.managers import TaggableManager
from django.core.urlresolvers import reverse

class Map(models.Model):
    author = models.ForeignKey('auth.User', verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Заголовок')

    tags = TaggableManager(blank=True, verbose_name='Тэги')

    file = models.ImageField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='Файл'
    )
    description = models.TextField(max_length=200, verbose_name='Опис', blank=True)

    created_date = models.DateTimeField(default=timezone.now, verbose_name='Дата створення')
    modifed_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата редагування')

    @property
    def short_title(self):
        return truncatechars(self.title, 100)

    def _tags(self):
        return [t.name for t in self.tags.all()]

    def get_absolute_url(self):
        return reverse('map', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Мапа'
        verbose_name_plural = 'Мапи'
        permissions = (
            ('moderate_cmspost', 'Модерація мап'),
            ('map_access', 'Доступ до мап'),
        )

app/cms/forms/comment.py
from django import forms

from cms.models.comment import Comment


class CommentForm(forms.ModelForm):

  class Meta:
    fields = ('text',)
    model = Comment

app/cms/views/ajax.py
from django.http import JsonResponse

from taggit.models import Tag


def get_simular_tags(request):
    query = request.GET.get('term')
    tags = Tag.objects.filter(name__icontains=query).values('name')

    result = []

    for tag in tags:
        result.append(tag['name'])

    return JsonResponse(list(result), safe=False)

app/cms/views/comment.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone
from django.core.exceptions import PermissionDenied

from cms.utils import is_owner
from django.shortcuts import get_object_or_404
from cms.forms.comment import CommentForm

from cms.models.cmspost import CmsPost
from cms.models.comment import Comment


@login_required
@permission_required('cms.add_comment', raise_exception=True)
def comment_new(request, pk):
    post = get_object_or_404(CmsPost, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            return get_comment_url(post.pk, comment.pk)

    return redirect('post_detail', pk=post.pk)


@login_required
@permission_required('cms.change_comment', raise_exception=True)
def comment_edit(request, pk, cpk):
    post = get_object_or_404(CmsPost, pk=pk)
    comment = get_object_or_404(Comment, pk=cpk)

    if not is_owner(request.user, comment):
        raise PermissionDenied()

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.modifed_date = timezone.now()
            comment.save()

            return get_comment_url(post.pk, comment.pk)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'cms/comment_edit.html', {'form': form})


@login_required
@permission_required('cms.add_comment', raise_exception=True)
def comment_reply(request, pk, cpk):
    post = get_object_or_404(CmsPost, pk=pk)
    parent = get_object_or_404(Comment, pk=cpk)

    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.parent = parent
            comment.save()

            return get_comment_url(post.pk, comment.pk)
    else:
        form = CommentForm()

    return render(request, 'cms/comment_edit.html', {'form': form, 'parent': parent})


@login_required
@permission_required('cms.delete_comment', raise_exception=True)
def comment_delete(request, pk, cpk):
    comment = get_object_or_404(Comment, pk=cpk)

    if not is_owner(request.user, comment):
        raise PermissionDenied()

    comment.is_deleted = True
    comment.save()

    return HttpResponseRedirect('%s#comments' % reverse('post_detail', kwargs={'pk': pk}))


def get_comment_url(pk, cpk):
    return HttpResponseRedirect('%s#comment%s' % (reverse('post_detail', kwargs={'pk': pk}), cpk))

app/cms/views/profile.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.db.models import Count, Q

from cms.forms.profile import ProfileForm, UserForm, UserSearchForm

from django.contrib.auth.models import User
from cms.models.cmspost import CmsPost

def profile(request, username=None):
    user = get_object_or_404(User, username=username)
    query = {
        'author': user
    }

    if request.user.is_authenticated and not user.has_perm('cms.permited_access'):
        query['is_permited'] = False

    posts = CmsPost.objects.filter(Q(**query)).distinct().order_by('-created_date')[0:30]

    return render(request, 'registration/profile.html', { 'profile_user': user, 'posts': posts })

@login_required
def my_profile(request):
    return profile(request, request.user)

@login_required
@transaction.atomic
def profile_edit(request, username=None):
    if username:
        user = get_object_or_404(User, username=username)
    else:
        user = request.user

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            if username:
                return redirect('profile', username=user.username)
            else:
                return redirect('me')

    else:
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)

    return render(request, 'registration/profile_edit.html', {
        'profile_user': user,
        'user_form': user_form,
        'profile_form': profile_form
    })

def userlist(request):
    query = {}
    if request.GET:
        form = UserSearchForm(request.GET)
        if form.is_valid():
            if form.cleaned_data['username']:
                query['username__icontains'] = form.cleaned_data['username']
            if form.cleaned_data['first_name']:
                query['first_name__icontains'] = form.cleaned_data['first_name']
            if form.cleaned_data['last_name']:
                query['last_name__icontains'] = form.cleaned_data['last_name']
    else:
        form = UserSearchForm()

    users_list = User.objects.annotate(posts_count=Count('cmspost', distinct=True))
    users_list = users_list.annotate(comments_count=Count('comment', distinct=True))
    users_list = users_list.filter(Q(**query)).order_by('username')
    page = request.GET.get('page', 1)

    paginator = Paginator(users_list, 5)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'registration/users_list.html', { 'users': users, 'form': form })

app/cms/templates/cms/comment_edit.html
{% extends 'cms/base.html' %}

{% block title %}
    {% if not parent %}
        Редагування коментаря
    {% else %}
        Відповідь на коментар: {{ parent.author }}
    {% endif %}
{% endblock %}

{% block content %}
    <h2>
        {% if not parent %}
            Редагування коментаря
        {% else %}
            Відповідь на коментар: {{ parent.author }}
        {% endif %}
    </h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit">Відправити</button>
    </form>
{% endblock %}

app/cms/templates/cms/comment_form.html
<form method="POST" id="comment-form" action="{% url 'comment_new' pk=post.pk %}">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Відправити</button>
</form>

app/cms/templates/cms/comment_posts.html
{% load comments %}

<ul>
    {% if posts %}
        {% for post in posts %}
            <li>
                <a href="{% url 'post_detail' post.pk %}#comment{{ post.last_comment.pk }}">
                    {{ post.title }}
                </a> -
                {{ post.last_comment.author }}
            </li>
        {% endfor %}
    {% else %}
        <ul>
            <li>Коментуємих постів поки немає</li>
        </ul>
    {% endif %}
</ul>

app/cms/templates/cms/donated.html
{% extends "cms/base.html" %}

{% block title %}
    Donate
{% endblock %}

{% block content %}
    <h1>Donate</h1>

    <p>Дякую, донат зараховано)</p>
    <p><a href="{{ request.scheme }}://{{ request.site }}/">На головну</a></p>
{% endblock %}

app/cms/templates/cms/map_edit.html
{% extends 'cms/base.html' %}
{% load staticfiles %}

{% block title %}
    {% if map %}
        Редягування мапи
    {% else %}
        Завантаження мапи
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% if map %}
            Редагування мапи
        {% else %}
            Завантаження мапи
        {% endif %}
    </h1>

    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit">Відправити</button>
    </form>
{% endblock %}

app/cms/templates/cms/map_list.html
{% extends 'cms/base.html' %}
{% load auth %}
{% load bleach_tags %}
{% load staticfiles %}
{% load opengraph %}
{% load tags_cloud %}
{% load comment_posts %}

{% block title %}
    {% if tags %}
        Мапи за тегами:
        {% for tag in tags %}
            {% if not forloop.first %}&nbsp;{% endif %}
            {{ tag }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    {% elif author %}
        Мапи користувача {{ author }}
    {% else %}
        Мапи
    {% endif %}
{% endblock %}

{% block og %}
    {% opengraph title=page_title %}
{% endblock %}

{% block content %}
    <div class="post-list">
        <div id="main">
            <h1>
                {% if tags %}
                    Мапи за тегами:
                    {% for tag in tags %}
                        {% if not forloop.first %}&nbsp;{% endif %}
                        {{ tag }}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                {% elif author %}
                    Мапи користувача {{ author }}
                {% else %}
                    Мапи
                {% endif %}
            </h1>

            {% if perms.cms.add_map %}
                <div class="actions">
                    <a href="{% url 'map_new' %}">Додати нову мапу</a>
                </div>
            {% endif %}

            <div class="posts">
                {% if not maps %}
                    <p class="nocontent">Поки що мап немає у розділі</p>
                {% endif %}

                {% for map in maps %}
                    <div class="post" id="{{ map.pk }}">
                        <div class="post-body">
                            <img src="{{ map.author.profile.avatar_url }}" alt="avatar" />

                            <div class="info">
                                <span>{{ map.author.first_name }} {{ map.author.last_name }} [<a class="username"
                                        href="{% url 'user' username=map.author.username %}">{{ map.author }}</a>]</span>
                                <span>{{ map.created_date }}</span>
                                {% if map.modifed_date %}
                                    <span>[відредаговано {{ map.modifed_date }}]</span>
                                {% endif %}
                            </div>

                            <h2>
                                <a class="post-title" href="{% url 'map_file' pk=map.pk %}">{{ map.title }}</a>
                            </h2>


                            <div class="post-content clearfix">
                                {{ map.description|bleach }}
                            </div>
                        </div>

                        {% auth_is_owner map as is_map_owner %}
                        {% if is_map_owner %}
                            <div class="actions">

                                {% if perms.cms.change_map and is_map_owner %}
                                    <a href="{% url 'map_edit' pk=map.pk %}">Редагувати</a>
                                {% endif %}

                                {% if perms.cms.delete_map and is_map_owner %}
                                    <a href="{% url 'map_delete' pk=map.pk %}"
                                       onclick="return confirm('Ви впевнені, що хочете видалити мапу?')">
                                        Видалити
                                    </a>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}

            </div>

            {% if posts.has_other_pages %}
                <ul class="pagination">
                    {% if posts.has_previous %}
                        <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                        {% if posts.number == i %}
                            <li class="active"><span>{{ i }}</span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
        <div id="sidebar">
            <div>
                <h3>Категорії</h3>
                <div class="block categories">
                    <ul>
                        <li><a href="/">Всі пости</a></li>
                        {% for category in categories_list %}
                            <li>
                                <a href="{% url 'category_list' category=category.route %}">{{ category }}</a>
                                ({{ category.posts_count }})
                            </li>
                        {% endfor %}
                        <li>
                            <a href="{% url 'maps_list' %}">Мапи</a>
                            ({{ maps_count }})
                        </li>
                    </ul>
                </div>
            </div>
            <div>
                <h3>Теги</h3>
                <div class="block tags">
                    {% maps_tags_cloud as cloud %}
                    {% for tag in cloud %}
                        <a href="{% url 'maps_tag_list' tags=tag.name %}"
                           class="tag-size-{{ tag.font_size }}">{{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>

            <div>
                <h3>Останні коментарі</h3>
                <div class="block list">
                    {% comment_posts 10 user %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/cms/templates/cms/post_detail.html
{% extends 'cms/base.html' %}
{% load comments %}
{% load auth %}
{% load bleach_tags %}
{% load opengraph %}
{% load bleach_src_filter %}

{% block title %}{{ post.title }}{% endblock %}

{% block og %}
    {% if post.category.route == 'photo' or post.category.route == 'drawing' %}
        {% opengraph title=post.title description=post.description image=post.file %}
    {% else %}
        {% opengraph title=post.title description=post.text|striptags|truncatechars:400 %}
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="/">Блог</a></li>
    <li>
        <a href="{% url 'category_list' category=post.category.route %}">
            {{ post.category.name }}
        </a>
    </li>
{% endblock %}

{% block content %}
    {% comment_count as comm_count %}
    <div class="post single">
        <div class="post-body">
            <img src="{{ post.author.profile.avatar_url }}" alt="avatar"/>
            <div class="info">
                {% if post.is_permited %}
                    <span><i class="fas fa-lock" title="Прихованний пост"></i></span>
                {% endif %}
                <span>{{ post.created_date }}</span>
                <span>{{ post.author.first_name }} {{ post.author.last_name }} [<a class="username"
                        href="{% url 'user' username=post.author.username %}">{{ post.author }}</a>]</span>
                {% if post.modifed_date %}
                    <span>[відредаговано {{ post.modifed_date }}]</span>
                {% endif %}
            </div>

            <h1>{{ post.title }}</h1>

            <div class="post-content clearfix">
                {{ post.text|bleach_src|bleach }}
            </div>

            {% if post.tags.all %}
                <div class="tags">
                    {% for tag in post.tags.all %}
                        {% if not forloop.first %}&nbsp;{% endif %}
                        <a href="{% url 'tag_list' tags=tag.name %}">#{{ tag.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        {% if user.is_authenticated and perms.cms.add_comment %}
            <div class="actions">
                {% auth_is_owner post as is_post_owner %}

                {% if perms.cms.change_cmspost and is_post_owner %}
                    <a href="{% url 'post_edit' pk=post.pk %}">Редагувати</a>
                {% endif %}

                {% if perms.cms.delete_cmspost and is_post_owner %}
                    <a href="{% url 'post_delete' pk=post.pk %}"
                       onclick="return confirm('Ви впевнені, що хочете видалити пост?')">
                        Видалити
                    </a>
                {% endif %}

                {% if perms.cms.add_comment %}
                    <a href="#comment-form">Коментувати</a>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <div class="comments" id="comments">
        {% if comm_count %}{% comment_list %}{% endif %}
        {% clear_unread_comments %}

        {% if perms.cms.add_comment %}
            {% comment_form post %}
        {% else %}
            <p class="not-allowed-comments">Увійдіть або зареєструйтеся щоб додавати коментарі</p>
        {% endif %}
    </div>
{% endblock %}